
samples:

  Target_Events: 1_000_000

  files:

    bbbb_signal:
      directory: "/storage/epp2/phubsg/bbbb_samples/bbbb_signal_mc/mc20/"
      files:
      - "combined_skim_ggFhh_chhh1p0_mc20a__Nominal.parquet"
      - "combined_skim_ggFhh_chhh1p0_mc20d__Nominal.parquet"
      - "combined_skim_ggFhh_chhh1p0_mc20e__Nominal.parquet"
      save_name: "bbbb_sig_1p0_run2"
      selections:
        - ["pass_resolved",""]
        - ["ntag", "==4"] 
        - ["X_hh","<1.6"]
        - ["dEta_hh","<1.5"]
      smear: False

    bb_background:
      directory: "/storage/epp2/phubsg/bbbb_samples/bb_background_data/"
      files:
      - "combined_skim_data15__Nominal.parquet"
      - "combined_skim_data16__Nominal.parquet"
      - "combined_skim_data17__Nominal.parquet"
      - "combined_skim_data18__Nominal.parquet"
      save_name: "bb_bkg_run2"
      selections:
        - ["pass_resolved",""]
        - ["ntag", "==2"] 
        - ["X_hh","<1.6"]
        - ["dEta_hh","<1.5"]
      smear: False

    bbbb_background:
      directory: "/storage/epp2/phubsg/bbbb_samples/bbbb_background_prediction/20250723_resolved/data161718-gn277_4b_sr_124_117_cr_x1.6_ggf_resolved_resolved_blind_h1h2_run2/predictions/"
      files:
      - "df_pred__pipe_16_10xGP_mean.parquet"
      - "df_pred__pipe_17_10xGP_mean.parquet"
      - "df_pred__pipe_18_10xGP_mean.parquet"
      save_name: "bbbb_bkg_run2"
      selections:
        - ["X_hh","<1.6"]
        - ["dEta_hh","<1.5"]
      smear: False

variables:
  - X_hh
  - pt_h1
  - pt_h2
  - eta_h1
  - eta_h2
  - m_hh
  - dEta_hh
  - m_h1
  - m_h2
  - X_wt_tag

training:

  add_name: "ADDNAME"

  Signal_file: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bbbb_sig_1p0_run2/"
  Data_file: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bb_bkg_run2/"
  Background_file: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bbbb_bkg_run2/"

  # add_name: "20.08.25"

  # signal: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bbbb_sig_1p0_run2/"
  # background: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bb_bkg_run2/"

  # signal_name: "bbbb_sig"
  # background_name: "bb_data"

  # signal: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bb_bkg_run2/"
  # background: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bbbb_bkg_run2/"

  # signal_name: "bb_data"
  # background_name: "bbbb_bkg"

  # signal: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bbbb_sig_1p0_run2/"
  # background: "/home/epp/phubsg/Postgrad/HH_BBBB/MVA_dicriminant/samples/bbbb_bkg_run2/"

  # signal_name: "bbbb_sig"
  # background_name: "bbbb_bkg"

  structure:
    hidden_layers:
      - 128
      - 128

  learning:
    optimizer: "Adam"
    scheduler: "Cosine"
    batch_size: 256
    learning_rate: 1e-3
    epochs: 400
