
net_name: Testing_256_256_256_256_256_256_256_1em4_50

inputs:

  files:
  
    signal_dir: "/storage/epp2/phubsg/bbbb_samples/bbbb_signal_mc/mc20/"
    signal_files: 
      - "combined_skim_ggFhh_chhh1p0_mc20a__Nominal.parquet"
      - "combined_skim_ggFhh_chhh1p0_mc20d__Nominal.parquet"
      - "combined_skim_ggFhh_chhh1p0_mc20e__Nominal.parquet"

    background_dir: "/storage/epp2/phubsg/bbbb_samples/bb_background_data/"
    background_files:
      - "combined_skim_data15__Nominal.parquet"
      - "combined_skim_data16__Nominal.parquet"
      - "combined_skim_data17__Nominal.parquet"
      - "combined_skim_data18__Nominal.parquet"

    N_batches: 1000
    batch_size: 1000


  variables:
    - X_hh
    - pt_h1
    - pt_h2
    - eta_h1
    - eta_h2
    - m_hh
    - dEta_hh
    - m_h1
    - m_h2
    - dPhi_hh
    - X_wt_tag

  selections:
    signal:
      - ["pass_resolved",""]
      - ["ntag", "==4"]
      # - ["njets", ">=4"]
    background:
      - ["pass_resolved",""]
      - ["ntag", "==2"]
      # - ["njets", "==4"]


hyper_params:

  network:
    hidden_layer_structure:
      - 256
      - 256
      - 256
      - 256
      - 256
      - 256
      - 256

  training:
    batch_size: 256
    learning_rate: 1e-4
    epochs: 50

